### PR TITLE
Ready for review (gh-pages)

### PR DESCRIPTION
**Pull request by BrittanyBlake**
## Design Teardown

-Added grayscale navbar with hover property.
-Added graysclale main content section with different articles.
-Added grayscale footer section.

[Live Version](https://brittanyblake.github.io/Design-Teardown/)

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @BrittanyBlake and @Buyaki01 

### You have both done a good job so far :clap: However, there is a change
- In your HTML code, use HTML5 semantics. For example in your code use the tag `article` instead of `div` Refer attached image
Screenshot from 2020-02-12 13-16-48

- Make the change and resubmit for another coding review.
- Happy coding!
- For Assistance: Contact me on @rOluochKe

**Comment by BrittanyBlake** [comment]
## Design Teardown

-Changed the div tags to article tags.

[Live Version](https://brittanyblake.github.io/Design-Teardown/)

**Comment by BrittanyBlake** [comment]
## Design Teardown

-Changed the div tags to article tags.
-Changed HTML validator warnings. 

[Live Version](https://brittanyblake.github.io/Design-Teardown/)

**Review by nikasulo — APPROVED** [review]
# Awesome effort @BrittanyBlake ! :medal_military: 
Great job building this and implementing the changes suggested! Please merge this and keep up the maximum effort :handshake: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
